# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Quiz IT Easy CD Release

on:
  push:
    branches: [release, main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Verify build
        run: dotnet build --no-restore

      - name: Check formatting
        run: dotnet format --verify-no-changes

      - name: Run test
        run: dotnet test --no-build --verbosity normal

      - name: 'Login to ACR'
        if: success()
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push docker image to ACR
        if: success()
        run: |
          docker build -f src/QuizItEasy.API/Dockerfile . -t ${{ secrets.ACR_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
